version: "3.7"

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    networks:
      - network-backend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./storage:/storage

  backend:
    build: backend
    ports:
      - 8000:8000
    networks:
      - network-backend
    volumes:
      - ./backend:/app
      - ./storage:/storage
