version: '3.8'

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
  
  fastapi:
    container_name: fastapi
    build:
      context: .\backend_2
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment: 
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/Emotion_db
    depends_on:
      - db
    restart: always
    volumes:
      - .:/fastapi

  frontend:
    build:
      context: .\frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - fastapi
    volumes:
      - /frontend
  